# Generated by Django 5.2.6 on 2025-09-23 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=160, unique=True)),
                ('difficulty', models.CharField(blank=True, choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('platform', models.CharField(blank=True, choices=[('VulnHub', 'VulnHub'), ('HackThebox', 'HackThebox'), ('TryHackMe', 'TryHackMe'), ('OverTheWire', 'OverTheWire')], max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='machines/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='machines.machine')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('machine', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='machines.section')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('section', 'order')},
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='tags',
            field=models.ManyToManyField(blank=True, to='machines.tag'),
        ),
        migrations.CreateModel(
            name='StepBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('description', 'Description'), ('code', 'Code'), ('image', 'Image'), ('markdown', 'Markdown')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.TextField(blank=True, help_text='Para description/markdown')),
                ('code', models.TextField(blank=True, help_text='Para bloques de código')),
                ('image', models.ImageField(blank=True, null=True, upload_to='machines/steps/')),
                ('caption', models.CharField(blank=True, max_length=250)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='machines.step')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('step', 'order')},
            },
        ),
    ]
