# Generated by Django 5.2.6 on 2025-09-25 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('emoji', models.CharField(help_text='Ej: 😊', max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('contact_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='objetivo', to='contact.contactpage')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveSubsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsecciones', to='contact.objective')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=200)),
                ('profesion', models.CharField(max_length=200)),
                ('contact_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='contact.contactpage')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('tipo', models.CharField(max_length=100)),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listados', to='contact.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('listado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contact.personallist')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=200, null=True)),
                ('descripcion', models.TextField()),
                ('version', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('En progreso', 'En progreso'), ('Terminado', 'Terminado')], max_length=50)),
                ('color', models.CharField(default='gray', max_length=20)),
                ('contact_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='contact.contactpage')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tecnologias', to='contact.personalproject')),
            ],
        ),
    ]
