# Generated by Django 5.2.6 on 2025-09-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactpage_objective_objectivesubsection_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalproject',
            old_name='color',
            new_name='color_background',
        ),
        migrations.AddField(
            model_name='personalproject',
            name='color_border',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='color_emoji',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='color_technology',
            field=models.CharField(default='gray', max_length=20),
        ),
        migrations.AddField(
            model_name='personalproject',
            name='color_title',
            field=models.CharField(default='gray', max_length=20),
        ),
    ]
