# Generated by Django 5.2.6 on 2025-09-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_color_personalproject_color_background_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalproject',
            name='color_emoji',
        ),
        migrations.AddField(
            model_name='personalproject',
            name='coloremoji',
            field=models.CharField(default='gray', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='color_background',
            field=models.CharField(default='gray', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='color_border',
            field=models.CharField(default='gray', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='color_technology',
            field=models.CharField(default='gray', max_length=150),
        ),
        migrations.AlterField(
            model_name='personalproject',
            name='color_title',
            field=models.CharField(default='gray', max_length=150),
        ),
    ]
