# Generated by Django 5.2.6 on 2025-09-26 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_personalproject_color_emoji_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalproject',
            old_name='coloremoji',
            new_name='color_emoji',
        ),
    ]
