# Generated by Django 5.2.6 on 2025-09-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_coloremoji_personalproject_color_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalproject',
            name='color_technology_background',
            field=models.CharField(default='gray', max_length=150),
        ),
    ]
