# Generated by Django 5.2.6 on 2025-09-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Título por defecto', max_length=200)),
                ('subtitulo', models.CharField(default='Subtítulo por defecto', max_length=300)),
                ('card_titulo', models.CharField(max_length=200)),
                ('card_emoji', models.CharField(help_text='Ej: 🚀', max_length=10)),
                ('card_descripcion', models.TextField()),
                ('boton_1_texto', models.CharField(blank=True, max_length=50, null=True)),
                ('boton_1_url', models.URLField(blank=True, null=True)),
                ('boton_2_texto', models.CharField(blank=True, max_length=50, null=True)),
                ('boton_2_url', models.URLField(blank=True, null=True)),
                ('boton_3_texto', models.CharField(blank=True, max_length=50, null=True)),
                ('boton_3_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Configuración de Home',
                'verbose_name_plural': 'Configuración de Home',
            },
        ),
    ]
