# Generated by Django 5.2.6 on 2025-09-25 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('emoji', models.CharField(help_text='Ejemplo: 🚀', max_length=10)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('emoji', models.CharField(help_text='Ejemplo: 💡', max_length=10)),
                ('descripcion', models.TextField()),
                ('seccion', models.CharField(choices=[('principal', 'Card Principal'), ('tres', 'Grupo de 3 Cards'), ('dos', 'Grupo de 2 Cards')], max_length=20)),
                ('about_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='about.aboutpage')),
            ],
        ),
    ]
